spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/workflowdb?stringtype=unspecified&options=-c%20TimeZone=Asia/Kolkata
    username: workflow
    password: workflow123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: Asia/Kolkata

logging:
  level:
    root: INFO
